# Generated by Django 5.2 on 2025-08-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0004_tickethistory_tva_amount_tickethistory_tva_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionhistory',
            name='image',
            field=models.FileField(upload_to='tickets/'),
        ),
    ]
